version: '3.8'

services:
  # Django backend
  backend:
    build: .
    restart: unless-stopped
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:9000 --workers 3 --timeout 120"
    volumes:
#      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/static
    ports:
      - "9000:9000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,kanban.leonberkemeier.de
      - SECRET_KEY=xV9r8Qf2zP7yLw3N_aHk5sR0mUeBvY6cTqJ4nFzG
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/tasks/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  static_volume:
