# Generated by Django 5.2.6 on 2025-09-30 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('column', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To-Do'), ('in_progress', 'In Progress'), ('review', 'Review/Testing'), ('done', 'Done')], default='backlog', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('assignee', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
