# Generated by Django 5.2.6 on 2025-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_information',
            field=models.TextField(blank=True, help_text='Detailed information only visible in task details'),
        ),
    ]
